AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  FrontSecurityGroup:
    Type: String
  BackSecurityGroup:
    Type: String
  MyKeyName:
    Type: String
    Default: cf_aws_key
  FrontEC2InstanceName:
    Type: String
    Default: FrontEC2Instance
  BackEC2InstanceName:
    Type: String
    Default: BackEC2Instance

Resources:
  FrontEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03f2f5212f24db70a
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref FrontSecurityGroup
      KeyName: !Ref MyKeyName
      Tags:
        - Key: Name
          Value: !Ref FrontEC2InstanceName

  BackEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03f2f5212f24db70a
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref BackSecurityGroup
      KeyName: !Ref MyKeyName
      Tags:
        - Key: Name
          Value: !Ref BackEC2InstanceName

  FrontEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref FrontEC2Instance

  BackEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BackEC2Instance
