AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet2:
    Type: String
  FrontSecurityGroup:
    Type: String
  MyKeyName:
    Type: String
    Default: cf_aws_key
  EC2InstanceProfile:
    Type: String
  FrontEC2InstanceName:
    Type: String
    Default: FrontEC2Instance
  BackEC2PublicDNS:
    Type: String

Resources:
  FrontEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bd642e343e80eced
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref FrontSecurityGroup
      KeyName: !Ref MyKeyName
      Tags:
        - Key: Name
          Value: !Ref FrontEC2InstanceName
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            su ec2-user -c 'aws s3 cp s3://webapp-embedding-2023-0904/frontend.zip /home/ec2-user/frontend.zip'
            su ec2-user -c 'cd /home/ec2-user; unzip -o frontend.zip'
            su ec2-user -c 'aws s3 cp s3://webapp-embedding-2023-0904/frontend_env /home/ec2-user/frontend/.env'
            su ec2-user -c 'aws s3 cp s3://webapp-embedding-2023-0904/frontend-react-app_env /home/ec2-user/frontend/frontend-react-app/.env'
            echo "REACT_APP_ADDRESS_BACKEND=${BackEC2PublicDNS}" >> /home/ec2-user/frontend/frontend-react-app/.env
            su ec2-user -c 'cd /home/ec2-user/frontend/frontend-react-app; npm run build'
            su ec2-user -c 'sleep 5; pm2 start /home/ec2-user/frontend/frontend_node.js'
          - BackEC2PublicDNS: !Ref BackEC2PublicDNS

  FrontEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref FrontEIP
      InstanceId: !Ref FrontEC2Instance

  FrontEIP:
    Type: AWS::EC2::EIP

Outputs:
  FrontEC2Instance:
    Description: A reference to the created FrontEC2Instance
    Value: !Ref FrontEC2Instance
  FrontEIPAssociation:
    Description: A reference to the created FrontEIPAssociation
    Value: !Ref FrontEIPAssociation
  FrontEIP:
    Description: A reference to the created FrontEIP
    Value: !Ref FrontEIP 
  FrontEC2PublicDNS:
    Value: !GetAtt FrontEC2Instance.PublicDnsName
  