AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet2:
    Type: String
  ProxySecurityGroup:
    Type: String
  MyKeyName:
    Type: String
    Default: cf_aws_key
  EC2InstanceProfile:
    Type: String
  ProxyEC2InstanceName:
    Type: String
    Default: BackProxyEC2Instance
  BackEC2PrivateDNS:
    Type: String
  BackEC2Port:
    Type: String
    Default: 5001

Resources:
  ProxyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-032d7402806156fc7
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref ProxySecurityGroup
      KeyName: !Ref MyKeyName
      Tags:
        - Key: Name
          Value: !Ref ProxyEC2InstanceName
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            sed -i 's|ORIGIN_SERVER_NAME|${BackEC2PrivateDNS}|g' /etc/nginx/nginx.conf
            sed -i 's|ORIGIN_PROXY_PASS|http://${BackEC2PrivateDNS}|g' /etc/nginx/nginx.conf
            sed -i 's|ORIGIN_SERVER_PORT|${BackEC2Port}|g' /etc/nginx/nginx.conf
            service nginx start
          - BackEC2PrivateDNS: !Ref BackEC2PrivateDNS
            BackEC2Port: !Ref BackEC2Port

  ProxyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref ProxyEIP
      InstanceId: !Ref ProxyEC2Instance

  ProxyEIP:
    Type: AWS::EC2::EIP

Outputs:
  ProxyEC2Instance:
    Description: A reference to the created ProxyEC2Instance
    Value: !Ref ProxyEC2Instance
  ProxyEIPAssociation:
    Description: A reference to the created ProxyEIPAssociation
    Value: !Ref ProxyEIPAssociation
  ProxyEIP:
    Description: A reference to the created ProxyEIP
    Value: !Ref ProxyEIP 
  ProxyBackEC2PublicDNS:
    Value: !GetAtt ProxyEC2Instance.PublicDnsName
  