AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceType:
    Description: The EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
  KeyName:
    Description: Name of an existing EC2 key pair to allow SSH access to the instances
    Type: String
    Default: cf_aws_key
  LatestAmiId:
    Description: The latest Amazon Linux 2 AMI from the Parameter Store
    Type: String
    Default: ami-030293faa878df9aa
  OperatorEmail:
    Description: The email address to notify when there are any scaling activities
    Type: String
    Default: kokitabayashi@gmail.com
  PublicSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: At least two public subnets in different Availability Zones in the selected VPC
  PrivateSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Description: A virtual private cloud (VPC) that enables resources in public subnets to connect to the internet
  EC2InstanceProfile:
    Type: String

Resources:
  ELBBackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5001
        ToPort: 5001
        CidrIp: 0.0.0.0/0

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5001
        ToPort: 5001
        SourceSecurityGroupId:
          Fn::GetAtt:
          - ELBBackendSecurityGroup
          - GroupId
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  EC2BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: EC2BackendTargetGroup
      Port: 5001
      Protocol: HTTP
      HealthCheckPath: "/api/v2/health"
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPC

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EC2BackendTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 5001
      Protocol: HTTP

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'ElbBackend'
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !GetAtt ELBBackendSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: ElbBackend

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: 
          - !Ref EC2SecurityGroup
        IamInstanceProfile: 
          Name: !Ref EC2InstanceProfile
        UserData:
          Fn::Base64: |
            #!/bin/bash
            su ec2-user -c 'mkdir /home/ec2-user/dev'
            su ec2-user -c 'aws s3 cp s3://webapp-embedding-2023-0904/backend_elb.zip /home/ec2-user/dev/backend.zip'
            su ec2-user -c 'cd /home/ec2-user/dev; unzip -o backend.zip'
            su ec2-user -c 'aws s3 cp s3://webapp-embedding-2023-0904/backend_env /home/ec2-user/dev/backend/.env'
            su ec2-user -c 'sleep 5; pm2 start /home/ec2-user/dev/backend/backend_node.js'

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref OperatorEmail
          Protocol: email

  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: '3'
      MinSize: '2'
      NotificationConfigurations:
        - TopicARN: !Ref NotificationTopic
          NotificationTypes: ['autoscaling:EC2_INSTANCE_LAUNCH', 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR', 'autoscaling:EC2_INSTANCE_TERMINATE', 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR']
      TargetGroupARNs: [!Ref EC2BackendTargetGroup]
      VPCZoneIdentifier: !Ref PrivateSubnets

Outputs:
  BackEC2ElbDns:
    Value: !GetAtt ApplicationLoadBalancer.DNSName