AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-vpc.yaml
  
  IAMStackEC2S3Role:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-role-ec2-s3.yaml

  EC2StackBack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-ec2-backend.yaml
      Parameters:
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        BackSecurityGroup: !GetAtt VPCStack.Outputs.BackSecurityGroup
        EC2InstanceProfile: !GetAtt IAMStackEC2S3Role.Outputs.EC2InstanceProfile

  EC2StackProxyBack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-ec2-proxy-back.yaml
      Parameters:
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        ProxySecurityGroup: !GetAtt VPCStack.Outputs.ProxySecurityGroup
        EC2InstanceProfile: !GetAtt IAMStackEC2S3Role.Outputs.EC2InstanceProfile
        BackEC2PrivateDNS: !GetAtt EC2StackBack.Outputs.BackEC2PrivateDNS

  EC2StackFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-ec2-frontend.yaml
      Parameters:
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        FrontSecurityGroup: !GetAtt VPCStack.Outputs.FrontSecurityGroup
        EC2InstanceProfile: !GetAtt IAMStackEC2S3Role.Outputs.EC2InstanceProfile
        ProxyBackEC2PublicDNS: !GetAtt EC2StackProxyBack.Outputs.ProxyBackEC2PublicDNS

  EC2StackProxyFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-cloudformation-s3-bucket-2023-0901.s3.us-west-1.amazonaws.com/cf-ec2-proxy-front.yaml
      Parameters:
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        ProxySecurityGroup: !GetAtt VPCStack.Outputs.ProxySecurityGroup
        EC2InstanceProfile: !GetAtt IAMStackEC2S3Role.Outputs.EC2InstanceProfile
        FrontEC2PrivateDNS: !GetAtt EC2StackFront.Outputs.FrontEC2PrivateDNS